language: c

os:
  - linux

sudo: false

env:
  global:
    - PIP_DEPENDENCIES='pytest-cov coveralls'
    - CONDA_CHANNELS='astrofrog'
    - PYTHON_VERSION=2.7
    - TEST_SWITCH=False
  matrix:
    - CONDA_DEPENDENCIES='mock pytest pip coverage pyyaml requests pyside'
    - CONDA_DEPENDENCIES='mock pytest pip coverage pyyaml requests pyqt'
    - CONDA_DEPENDENCIES='mock pytest pip coverage pyyaml requests pyqt5'
    - CONDA_DEPENDENCIES='mock pytest pip coverage pyyaml requests pyqt pyside' TEST_SWITCH=True

before_install:

  # Install ci-helpers and set up conda
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

  # Setup system for headless GUI handling
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - if [ $TEST_SWITCH == True ]; then py.test --cov qt_helpers.py test_switch.py; fi
  - py.test test_qt_helpers.py

after_success:
  - coveralls
