language: c

os:
  - linux

before_install:
  - source continuous-integration/travis/install_conda_$TRAVIS_OS_NAME.sh

install:
  - conda create --yes -n test python=2.7
  - source activate test
  - conda install --yes mock pytest sip pyqt pyside pip coverage
  - pip install pytest-cov coveralls

script:
  - py.test --cov qt_helpers.py

after_success:
  - coveralls
